#!/bin/bash
camps_http="http://keplerscience.arc.nasa.gov/K2/GuestInvestigations.shtml"
for camp in `lynx -dump -nolist -accept_all_cookies "$camps_http" | awk '$1 ~ /^[0-9]/ { print $1}'` ; do
	printf -v camp2 "%02d" $camp
	invest_http="keplerscience.arc.nasa.gov/K2/GuestInvestigationsC${camp2}.shtml"
	#lynx -dump -nolist -accept_all_cookies "$invest_http" 
	for go_field in `lynx -dump -nolist \
		-accept_all_cookies "$invest_http" | egrep "GO" | awk 'BEGIN{ FS=" "} /([Bb]lazar|AGN|[Aa]ctive [Gg]alactic [Nn]uclei)/ {print $1}' `; do 
		echo "$camp--$go_field"
	done
done
